Object' is a special class name (rename Object to BaseObject)
php-xapi/model pull request #62
Opened 2018-04-04 03:25 UTC by djoudi

Object' is a special class name (rename Object to BaseObject)

2018-04-04 03:25 UTC, djoudi commented
Object' is a special class name (rename Object to BaseObject)

2018-04-04 03:32 UTC, djoudi commented
Object is now a reserved class name in PHP 7.2

2018-04-04 06:03 UTC, xabbuh commented on composer.json
> +    "name": "djoudi/model",
please revert this change

2018-04-04 06:04 UTC, xabbuh commented
I would have expected changes in other classes that extend the base `Object` class.

2018-04-04 15:45 UTC, djoudi reviewed
update

2018-04-04 15:45 UTC, djoudi commented on composer.json
> +    "name": "djoudi/model",
Ok now

2018-04-05 12:25 UTC, xabbuh requested changes
This still needs changes in the other classes that still reference the old name (you can take a look at the failing Travis CI build).

2018-04-05 12:26 UTC, djoudi commented
waiting accepted ...

2018-04-05 13:07 UTC, xabbuh commented
Let's use `StatementObject` as the class name and make this change consistently throughout the code base.

2018-04-06 06:40 UTC, djoudi commented
check now

2018-04-08 03:22 UTC, djoudi commented
waiting accepted ...

2018-04-08 07:22 UTC, xabbuh requested changes

2018-04-08 07:22 UTC, xabbuh commented on .gitignore
> +/.idea/
Please do not add this line. Editors are user specific and should therefore be added to your global `.gitignore` file if any

2018-04-08 07:22 UTC, xabbuh commented on .idea/composerJson.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file and all other files from the `.idea` directory

2018-04-08 14:09 UTC, closed without merging